{% set version = "0.6.0" %}
{% set torch_proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}

package:
  name: pyg-lib
  version: {{ version }}

source:
  - url: https://github.com/pyg-team/pyg-lib/archive/refs/tags/{{ version }}.tar.gz
    sha256: 6fbdcc4e1a47891abbe4a58ffaa38e3bc4ad340faba2ba9d9500bdaa88a78427
    patches:
      - patches/0001-fix-cmake.patch
      # due to https://github.com/conda-forge/pytorch-cpu-feedstock/issues/357
      - patches/0002-look-harder-for-pytorch.patch

  - folder: third_party/cccl
    git_url: https://github.com/NVIDIA/cccl.git
    git_rev: d84981c797eb186e45f883f85423df94f9ac8bf4

  - folder: third_party/cuCollections
    git_url: https://github.com/NVIDIA/cuCollections.git
    git_rev: 8333a0beb551bc1a46314840de3c28b855564ccb

  - folder: third_party/METIS
    git_url: https://github.com/KarypisLab/METIS.git
    git_rev: 22008804e8c9b78893ae10a94c0d8b4b592438b4

build:
  number: 5
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}                             # [cuda_compiler_version != "None"]
    - python                                             # [build_platform != target_platform]
    - cross-python_{{ target_platform }}                 # [build_platform != target_platform]
    - cmake
    - ninja
  host:
    - python
    - pip
    - setuptools
    - pytorch
    - pytorch * {{ torch_proc_type }}*
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - parallel-hashmap
    {% if cuda_compiler_version != "None" %}
    - cuda-version =={{ cuda_compiler_version }}
    - cuda-cudart-dev
    # No cuda-driver-dev in windows
    - cuda-driver-dev  # [linux]
    - cuda-nvrtc-dev
    - cuda-nvtx-dev
    - cuda-profiler-api
    - cutlass
    - libcublas-dev
    - libcufft-dev
    - libcurand-dev
    - libcusolver-dev
    - libcusparse-dev
    - nvtx-c
    {% endif %}
  run:
    - python
    - parallel-hashmap
    - triton                                 # [linux and cuda_compiler_version not in (undefined, 'None')]
    - cutlass                                # [cuda_compiler_version not in (undefined, 'None')]
  run_constrained:
    # additional run constraint to the one from the (version-only) run_export;
    # constraining the CPU builds to CPU pytorch isn't 100% necessary, but cleaner
    - pytorch * {{ torch_proc_type }}*

test:
  imports:
    - pyg_lib
  requires:
    - pytest
  source_files:
    - test/
  commands:
    - pytest

about:
  home: https://github.com/pyg-team/pyg-lib
  summary: Low-Level Graph Neural Network Operators for PyG
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pyg-team/pyg-lib

extra:
  recipe-maintainers:
    - rusty1s
    - RaulPPelaez
    - h-vetinari
